#!/bin/bash
chmod ug+rwx hello
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
6-multiple_permissions [unix] (14:50 05/03/2022)                         0,1 All
-- INSERT --

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
6-multiple_permissions [unix] (14:50 05/03/2022)                         0,1 All
-- INSERT --

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
6-multiple_permissions [unix] (14:50 05/03/2022)                         0,1 All
-- INSERT --

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
6-multiple_permissions [unix] (14:50 05/03/2022)                         0,1 All
-- INSERT --

